[ItemName]
BlackApricorn = "Black Apricorn"
BlueApricorn = "Blue Apricorn"
GreenApricorn = "Green Apricorn"
PinkApricorn = "Pink Apricorn"
RedApricorn = "Red Apricorn"
WhiteApricorn = "White Apricorn"
YellowApricorn = "Yellow Apricorn"

PokeBall = "Poké Ball"

[ItemTooltip]
# TODO: Set up a system for recycling tooltips?
BlackApricorn = "A special fruit seemingly related to berries.\nCan be used to craft assorted Poké Balls."
BlueApricorn = "A special fruit seemingly related to berries.\nCan be used to craft assorted Poké Balls."
GreenApricorn = "A special fruit seemingly related to berries.\nCan be used to craft assorted Poké Balls."
PinkApricorn = "A special fruit seemingly related to berries.\nCan be used to craft assorted Poké Balls."
RedApricorn = "A special fruit seemingly related to berries.\nCan be used to craft assorted Poké Balls."
WhiteApricorn = "A special fruit seemingly related to berries.\nCan be used to craft assorted Poké Balls."
YellowApricorn = "A special fruit seemingly related to berries.\nCan be used to craft assorted Poké Balls."

PokeBall = "A device for catching wild Pokémon.\nIt is thrown like a ball at the target.\nIt is designed as a capsule system."